version: '3.8'

services:
  app:
    build: .
    container_name: dt-money
    ports:
      - "5173:8000"
    depends_on:
      - json_server
    networks:
      - dtmoney
    tty: true
  json_server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "3333:3333"
    networks:
      - dtmoney

networks:
  dtmoney:
    driver: bridge